############################################################
# Atlas Custom Plugins made by Chelsea1124/HELIX
#
# Follow My Twitter to keep up with new projects!.
# https://twitter.com/HELIX______
#
# Sub to my YouTube channel for fun and amazing content!.
# https://www.youtube.com/chelsea1124HD
#
# Join my discord to speak with others and me when im coding!.
# If you also need support join the discord below.
# https://discord.gg/8s3MSg7
#
###########################################################



BlackSmith:
  InventoryName: "&9&lBlackSmith!"

Shop:
  InventoryName: "&9&lShop!"
  FillerName: "&c&lT&6&lE&e&lS&2&lT &b&lD&9&lI&5&lE&f&l!!!"
  FillerLore:
  - "&c&lL&6&lO&e&lR&2&lE &b&lD&9&lI&5&lE&f&l!!!"
  GodlyEnchantsList:
    GodlyEnchantsName: "&c&lGodly Enchants!"
    FearSightName: "&c&lFearSight Enchantment"
    FearSightLore:
    - "&eThis &cGODLY Enchantment &eGives the ability to see mobs through blocks!"
    - "&c&lFearSight &ealso has 3 Different levels granting different effects."
    - "&edependent on how high of a level the enchantment may be."
    - ""
    - "&c&l◆ &9Tier I &7| &95 Block Distance &7| &ePrice &9&l21 &eDiamonds"
    - "&c&l◆ &9Tier II &7| &910 Block Distance &7| &ePrice &9&l32 &eDiamonds"
    - "&c&l◆ &9Tier III &7| &915 Block Distance &7| &ePrice &9&l64 &eDiamonds"
  FearSightShop:
    FearSightShopName: "&c&lFearSight Shop!"
    FearSight1: "&c&lFearSight I"
    FearSight1Lore:
      - "&eThis enchantment gives the ability to see mobs through &c5 &eblocks!"
      - ""
      - "&c&lBUY NOW!"
      - "&921 Diamonds!"
      - ""
      - "&c&lHow To Apply"
      - "&7Drag and drop this Enchant onto a &eHelmet!"
      - ""
      - "&4&lWARNING NO REFUND"
    FearSight2: "&c&lFearSight II"
    FearSight2Lore:
      - "&eThis enchantment gives the ability to see mobs through &c10 &eblocks!"
      - ""
      - "&c&lBUY NOW!"
      - "&932 Diamonds!"
      - ""
      - "&c&lHow To Apply"
      - "&7Drag and drop this Enchant onto a &eHelmet!"
      - ""
      - "&4&lWARNING NO REFUND"
    FearSight3: "&c&lFearSight III"
    FearSight3Lore:
      - "&eThis enchantment gives the ability to see mobs through &c15 &eblocks!"
      - ""
      - "&c&lBUY NOW!"
      - "&964 Diamonds!"
      - ""
      - "&c&lHow To Apply"
      - "&7Drag and drop this Enchant onto a &eHelmet!"
      - ""
      - "&4&lWARNING NO REFUND"

Messages:
  tag-prefix: "&6&lAtlasEnchants"
  inventory-full: "&cYour Inventory is full so cant open blacksmith"
  max-enchant-message: "&cYou already reached the max level of the enchant"
  enchant-error-message: "&cYou can't use more than one enchant item."
  inventory-full-message-onopen: "&cYour inventory is full or you haven't 2 free slots."
  inventory-full-message-onclose: "&cYour inventory is full. Your items are on the ground!"
  no-diamond: "&cYou don't have enough diamonds to upgrade it."

Fearsight:
  #Type of Item the Enchant is
  customItem: HEART_OF_THE_SEA
  #Lore for the Enchant
  lore-for-Fearsight: "&7This enchantment gives the ability to see mobs through blocks!"
  #Colour of the Glow per Mob Type
  Monster-GLOW-Colour: DARK_RED
  Passive-GLOW-Colour: DARK_GREEN
  Player-Villager: WHITE
  #Radius of how far the glow goes per Tier
  radius-of-glowing-1: 5
  radius-of-glowing-2: 10
  radius-of-glowing-3: 15
  #Cost per Upgrade
  amount-of-diamonds-to-level-2: 10
  amount-of-diamonds-to-level-3: 15